# Generated by Django 4.2.3 on 2024-03-20 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crimeapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CrimePrediction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit_name', models.CharField(max_length=100)),
                ('district_name', models.CharField(max_length=100)),
                ('crime_head_name', models.CharField(max_length=100)),
                ('crime_group', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='globalconfig',
            name='status',
            field=models.CharField(choices=[('Enabled', 'Enabled'), ('Disabled', 'Disabled')], max_length=10),
        ),
        migrations.AlterField(
            model_name='public',
            name='age',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='public',
            name='gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], max_length=10),
        ),
        migrations.AlterField(
            model_name='public',
            name='phone',
            field=models.CharField(max_length=15),
        ),
    ]
