# Generated by Django 4.2.3 on 2024-03-20 16:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crimeapp', '0003_crimedata'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CrimeData',
        ),
    ]
