# Generated by Django 4.2.3 on 2024-03-21 01:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crimeapp', '0005_public_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='public',
            name='user',
        ),
    ]
